CREATE OR ALTER   PROCEDURE [DBO].[USP_USER_EXPENSE_CHART]
(
@USER_ID VARCHAR(50)
)
AS

DROP TABLE IF EXISTS #TEMP_DATE_TABLE

CREATE TABLE #TEMP_DATE_TABLE([DATE] DATE)

DECLARE @LATESTDATE DATE=(SELECT TOP 1 [DATE] FROM BILLSUMMARY ORDER BY [DATE] DESC)
DECLARE @I INT = 0
WHILE @I<8
BEGIN
	INSERT INTO #TEMP_DATE_TABLE([DATE]) 
	VALUES(DATEADD(DAY,-@I,@LATESTDATE))
	SET @I=@I+1
END

SELECT CAST(TDT.DATE AS VARCHAR(20)) [DATE], ISNULL(SUM(BK.TOTALOFPERSON),0.00) AMT
FROM BILLSUMMARY BS
		LEFT JOIN BHUKKADS BK ON BS.ID = BK.BILLSUMMARYID AND BK.UserId = @USER_ID
		RIGHT JOIN #TEMP_DATE_TABLE TDT ON BS.[DATE]=TDT.[DATE] 
GROUP BY TDT.[DATE]
ORDER BY TDT.[DATE] 
